<?php
/**
 * Created by PhpStorm.
 * User: tungphung
 * Date: 7/3/17
 * Time: 3:09 PM
 */

namespace api\common\models;


class DeviceToken extends \common\models\DeviceToken
{
    public function  fields()
    {
        return parent::fields(); // TODO: Change the autogenerated stub
    }
}